### PR TITLE
[mlir][OpenMP] OpenMP Synchronization Hints stored as IntegerAttr

### PR DESCRIPTION
**Pull request by shraiysh**
`hint-expression` is an IntegerAttr, because it can be a combination
of multiple values from the enum omp_sync_hint_t (Section 2.17.12 of
OpenMP 5.0)

Differential Revision: https://reviews.llvm.org/D111360

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
Can you cherry-pick https://reviews.llvm.org/D112134 after you submit along with this patch?

**Comment by shraiysh** [comment]
Hi Kiran, I have cherry-picked the new differential too.

**Comment by shraiysh** [comment]
> > @sscalpone @schweitzpgi : Can you add @shraiysh to this repo so that he can add reviewers and request reviewers? @shraiysh works for Flang at AMD. Alternatively, is it OK if I do this from now on?
> 
> Invite sent.

Thanks for the invite @schweitzpgi!

**Comment by shraiysh** [comment]
Thanks for the rebase @jeanPerier. The changes in this PR are already a part of the fir-dev now (they went with the rebase). I will close this PR now.

**Comment by jeanPerier** [comment]
> Thanks for the rebase @jeanPerier. The changes in this PR are already a part of the fir-dev now (they went with the rebase). I will close this PR now.

Thanks for this PR @shraiysh, it helped to have it here while rebasing. I indeed had to apply it directly in the rebase given the new upstream changes.

**Pull request closed without merging**
