### PR TITLE
Cherry-pick front-end and runtime changes since PR 1243

### PR DESCRIPTION
**Pull request by vdonaldson**
78d6009 [flang] Deal with negative character lengths in semantics
394d6fc [flang] Check ArrayRef base for contiguity in IsSimplyContiguousHelper
d2124bf [flang] Remove default argument from function template specialization. NFC.
ea8cdf3 [flang] Fix a bug in INQUIRE(IOLENGTH=) output

### CODE REVIEW

**Review by psteinfeld — CHANGES_REQUESTED** [review]
Everything builds OK, but when I run `check-flang`, I see errors:
```
FAIL: Flang :: Fir/convert-to-llvm-invalid.fir (822 of 1280)
******************** TEST 'Flang :: Fir/convert-to-llvm-invalid.fir' FAILED ********************
Script:
--
: 'RUN: at line 3';   fir-opt --split-input-file --fir-to-llvm-ir="target=x86_64-unknown-linux-gnu" --verify-diagnostics /local/home/psteinfeld/cg/val/flang/test/Fir/convert-to-llvm-invalid.fir
--
Exit Code: 134

Command Output (stderr):
--
fir-opt: /local/home/psteinfeld/cg/b1/mlir/include/mlir/IR/TypeSupport.h:128: const mlir::AbstractType& mlir::TypeStorage::getAbstractType(): Assertion `abstractType && "Malformed type storage object."' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: fir-opt --split-input-file --fir-to-llvm-ir=target=x86_64-unknown-linux-gnu --verify-diagnostics /local/home/psteinfeld/cg/val/flang/test/Fir/convert-to-llvm-invalid.fir
 #0 0x0000000000b3461f PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000000000b31dae SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f148381cdd0 __restore_rt sigaction.c:0:0
 #3 0x00007f14822b170f raise (/lib64/libc.so.6+0x3770f)
 #4 0x00007f148229bb25 abort (/lib64/libc.so.6+0x21b25)
 #5 0x00007f148229b9f9 _nl_load_domain.cold.0 loadmsgcat.c:0:0
 #6 0x00007f14822a9cc6 .annobin___GI___assert_fail.end assert.c:0:0
 #7 0x000000000080e9d3 (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x80e9d3)
 #8 0x000000000080e9f9 (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x80e9f9)
 #9 0x0000000000649e91 mlir::LLVM::LLVMPointerType::get(mlir::Type, unsigned int) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x649e91)
#10 0x00000000004e7540 fir::LLVMTypeConverter::convertBoxType(fir::BoxType, int) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x4e7540)
#11 0x00000000004e7809 _ZNSt17_Function_handlerIFN4llvm8OptionalIN4mlir13LogicalResultEEENS2_4TypeERNS0_15SmallVectorImplIS5_EEEZNS2_13TypeConverter12wrapCallbackIN3fir7BoxTypeEZNSA_12wrapCallbackISD_ZNSC_17LLVMTypeConverterC4ENS2_8ModuleOpEEUlSD_E_EENSt9enable_ifIXsrNS0_6detail8detectorIvNSJ_12is_invocableEJT0_T_EE7value_tE5valueESt8functionIS9_EE4typeEOSM_EUlSD_S8_E_EENSI_IXntsrSP_5valueESR_E4typeESU_EUlS5_S8_E_E9_M_invokeERKSt9_Any_dataOS5_S8_ (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x4e7809)
#12 0x00000000008d5e86 mlir::TypeConverter::convertType(mlir::Type, llvm::SmallVectorImpl<mlir::Type>&) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x8d5e86)
#13 0x00000000008d6568 mlir::TypeConverter::convertType(mlir::Type) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x8d6568)
#14 0x00000000008c7f1d mlir::structFuncArgTypeConverter(mlir::LLVMTypeConverter&, mlir::Type, llvm::SmallVectorImpl<mlir::Type>&) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x8c7f1d)
#15 0x00000000008c6791 mlir::LLVMTypeConverter::convertFunctionSignature(mlir::FunctionType, bool, mlir::TypeConverter::SignatureConversion&) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x8c6791)
#16 0x000000000083d3a6 (anonymous namespace)::FuncOpConversionBase::convertFuncOpToLLVMFuncOp(mlir::FuncOp, mlir::ConversionPatternRewriter&) const StandardToLLVM.cpp:0:0
#17 0x000000000083e346 (anonymous namespace)::FuncOpConversion::matchAndRewrite(mlir::FuncOp, mlir::FuncOpAdaptor, mlir::ConversionPatternRewriter&) const StandardToLLVM.cpp:0:0
#18 0x00000000008308ea mlir::ConvertOpToLLVMPattern<mlir::FuncOp>::matchAndRewrite(mlir::Operation*, llvm::ArrayRef<mlir::Value>, mlir::ConversionPatternRewriter&) const (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x8308ea)
#19 0x00000000008d6985 mlir::ConversionPattern::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x8d6985)
#20 0x0000000000962b44 mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x962b44)
#21 0x00000000008dbf2b (anonymous namespace)::OperationLegalizer::legalize(mlir::Operation*, mlir::ConversionPatternRewriter&) DialectConversion.cpp:0:0
#22 0x00000000008de87c (anonymous namespace)::OperationConverter::convertOperations(llvm::ArrayRef<mlir::Operation*>) DialectConversion.cpp:0:0
#23 0x00000000008e1307 mlir::applyFullConversion(mlir::Operation*, mlir::ConversionTarget&, mlir::FrozenRewritePatternSet const&) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x8e1307)
#24 0x000000000050dad5 (anonymous namespace)::FIRToLLVMLowering::runOnOperation() CodeGen.cpp:0:0
#25 0x000000000081a6ca mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x81a6ca)
#26 0x000000000081aaa0 mlir::detail::OpToOpPassAdaptor::runPipeline(llvm::iterator_range<llvm::pointee_iterator<std::unique_ptr<mlir::Pass, std::default_delete<mlir::Pass> >*, mlir::Pass> >, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x81aaa0)
#27 0x000000000081bcd5 mlir::PassManager::run(mlir::Operation*) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x81bcd5)
#28 0x000000000089cecb performActions(llvm::raw_ostream&, bool, bool, llvm::SourceMgr&, mlir::MLIRContext*, mlir::PassPipelineCLParser const&) (.constprop.210) MlirOptMain.cpp:0:0
#29 0x000000000089d429 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, bool, bool, bool, bool, mlir::PassPipelineCLParser const&, mlir::DialectRegistry&, llvm::ThreadPool&) MlirOptMain.cpp:0:0
#30 0x000000000089d8e4 mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::PassPipelineCLParser const&, mlir::DialectRegistry&, bool, bool, bool, bool, bool)::'lambda'(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&)>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#31 0x0000000000ac63c4 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&)>, llvm::raw_ostream&) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0xac63c4)
#32 0x000000000089d807 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::PassPipelineCLParser const&, mlir::DialectRegistry&, bool, bool, bool, bool, bool) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x89d807)
#33 0x000000000089f29e mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&, bool) (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x89f29e)
#34 0x0000000000407396 main (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x407396)
#35 0x00007f148229d6a3 __libc_start_main (/lib64/libc.so.6+0x236a3)
#36 0x0000000000415c6e _start (/local/home/psteinfeld/cg/val/flang/build/bin/fir-opt+0x415c6e)
/local/home/psteinfeld/cg/val/flang/build/test/Fir/Output/convert-to-llvm-invalid.fir.script: line 1: 3270408 Aborted                 (core dumped) fir-opt --split-input-file --fir-to-llvm-ir="target=x86_64-unknown-linux-gnu" --verify-diagnostics /local/home/psteinfeld/cg/val/flang/test/Fir/convert-to-llvm-invalid.fir

--

********************
```

**Comment by vdonaldson** [comment]
> Everything builds OK, but when I run `check-flang`, I see errors:

That test had a conflict that I resolved in favor of retaining new test text.  I've switched to omitting it.

**Comment by psteinfeld** [comment]
> 
> 
> > Everything builds OK, but when I run `check-flang`, I see errors:
> 
> That test had a conflict that I resolved in favor of retaining new test text. I've switched to omitting it.

Thanks for the quick fix!  All is good now.

**Review by psteinfeld — APPROVED** [review]

**Comment by schweitzpgi** [comment]
> > Everything builds OK, but when I run `check-flang`, I see errors:
> 
> That test had a conflict that I resolved in favor of retaining new test text. I've switched to omitting it.

That doesn't sound right. Isn't this test checking basic error messages are being reported for invalid IR?

**Comment by vdonaldson** [comment]
> > > Everything builds OK, but when I run `check-flang`, I see errors:
> > 
> > 
> > That test had a conflict that I resolved in favor of retaining new test text. I've switched to omitting it.
> 
> That doesn't sound right. Isn't this test checking basic error messages are being reported for invalid IR?
> 
> (The crash in the traceback happens when Ops are created with null pointers and other badness.)

Commit 50acc6d - [flang][fir] Add missing `HasParent` in `fir_DTEntryOp` - is a small change to file FIROps.td.  But it modifies test `convert-to-llvm-invalid.fir` as one of a number of recent (upstreaming) changes to that test.  I've removed that commit from this umbrella commit to avoid conflicts.

**Comment by psteinfeld** [comment]
> 
> 
> > > > Everything builds OK, but when I run `check-flang`, I see errors:
> > > 
> > > 
> > > That test had a conflict that I resolved in favor of retaining new test text. I've switched to omitting it.
> > 
> > 
> > That doesn't sound right. Isn't this test checking basic error messages are being reported for invalid IR?
> > (The crash in the traceback happens when Ops are created with null pointers and other badness.)
> 
> Commit 50acc6d - [flang][fir] Add missing `HasParent` in `fir_DTEntryOp` - is a small change to file FIROps.td. But it modifies test `convert-to-llvm-invalid.fir` as one of a number of recent (upstreaming) changes to that test. I've removed that commit from this umbrella commit to avoid conflicts.

All still builds and tests correctly.

**Review by jeanPerier — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
