### PR TITLE
[flang] Initial lowering patch - WIP PR to prepare the phab patch

### PR DESCRIPTION
**Pull request by clementval**
### ! This is not meant to be merged. This is just a PR as a preview for a future patch.

This patch updates couple of files in `flang/include/flang/lower` and `flang/lib/lower` to enable the lowering of a basic empty program to FIR. 

- `flang/include/flang/Lower/FIRBuilder.h` and `flang/lib/Lower/FIRBuilder.cpp` are removed and replace by the newer version present in `flang/include/flang/Optimizer/Builder/FIRBuilder.h` and `flang/lib/Optimizer/Builder/FIRBuilder.cpp`.
- `flang/include/flang/Lower/Support/BoxValue.h` is removed and replace by the newer version present in `flang/include/flang/Optimizer/Builder/BoxValue.h`
- `flang/lib/Lower/SymbolMap.h` is moved to the proper include directory `flang/include/flang/Lower/SymbolMap.h`.
- `bbc` tool is introduced. It lowersFortran code down to MLIR/FIR. This initial patch is only able to lower a basic empty program to FIR.

This patch is part of the upstreaming effort from fir-dev branch.

As discussed previously, we tried to make a minimal initial patch instead of dropping lots of code at once.

### CODE REVIEW

**Review by schweitzpgi — COMMENTED** [review]
Nice work, Valentin.

Did you have to elide much from the bbc tool? Hopefully most of that can just be upstreamed.

**Comment by clementval** [comment]
> Nice work, Valentin.
> 
> Did you have to elide much from the bbc tool? Hopefully most of that can just be upstreamed.

Yeah I had to elide a good part otherwise it would bring lots of code with it. Since other big patches were not very welcomed in the past I tried to make it as small as possible.

**Comment by clementval** [comment]
First patch to remove obsolete files in this PR is live -> https://reviews.llvm.org/D118404
The second patch will come today.

**Comment by clementval** [comment]
I'm closing this since patches are up for review.

**Pull request closed without merging**
