### PR TITLE
[NFC] Explicitly map host associated symbols (do concurrent, OpenMP/OpenACC)

### PR DESCRIPTION
**Pull request by kiranchandramohan**
Explicitly map host associated symbols in DoConcurrent with shared locality-spec, clauses in OpenMP/OpenACC. The mapping of host-assoc symbols is set to their parent SymbolBox. This is achieved through a new interface function in the AbstractConverter.

Note:
A previous patch corrected this mapping for statement functions.
In a following patch I hope to remove "host association following" in symbol map lookups and "force" in "bindSymbol".

### CODE REVIEW

**Review by Leporacanthicus — COMMENTED** [review]
I've looked at this, I don't see anything obviously wrong, but I don't understand it well enough to say for sure that it's "good".

**Review by SouraVX — COMMENTED** [review]
Thanks for the patch @kiranchandramohan :)!
I tried this PR on a simple Worksharing OpenMP loop, doesn't notice any difference WRT induction variable in FIR.
Is this Okay ?
Is it possible to add/provide a test case which exercise this change.

**Comment by kiranchandramohan** [comment]
Thanks @SouraVX for having a look. I will try to explain below.

All OpenMP symbols in clauses have host-association. While lowering OpenMP clauses, a function `converter.getSymbolAddress(sym)` is called. This function usually gets the MLIR value corresponding to the symbol. For those symbols which have host-association, it gets the MLIR value corresponding to its associated host symbol. Getting the associated host symbol is correct for OpenMP clauses like shared but it is not correct if the clause is private. https://github.com/flang-compiler/f18-llvm-project/pull/752 removes the getting of the associated host symbol. If we want the same behaviour then this functionality has to replicated in the lowering of OpenMP clauses. This patch does that. We will later explicitly handle privatisation.

https://github.com/flang-compiler/f18-llvm-project/pull/753 handles privatisation of sequential loop indices in the parallel region. It has a testcase.

May be I should add an NFC tag for this PR.

**Review by jeanPerier — APPROVED** [review]
So there were already more cases depending on the HostAssociated symbol lookup behavior than statement functions. What you did here makes sense to me, Thanks Kiran.

**Pull request merged**
