### PR TITLE
Basic support for gtest infra

### PR DESCRIPTION
**Pull request by Sameeranjoshi**
I tried building using `-DLLVM_BUILD_TESTS=ON`
I couldn't find any `check-flang-optimizer` target nor `check-flang-unit target`
The test is a dummy test, would work on that aggressively once the setup in done.

Can anyone from here guide on what information I might be missing?

### CODE REVIEW

**Comment by banach-space** [comment]
Perhaps missing `add_subdirectory(unittests)` in the top CMake script for Flang?

Btw, the target that you've defined here is `FlangUnitTests` rather than `check-flang-optimizer` or `check-flang-unit` (i.e. try building `FlangUnitTests` instead).

**Comment by schweitzpgi** [comment]
The flang/CMakeLists.txt file probably needs some more work. For example, clang has the following to set up its testing.

https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/clang/CMakeLists.txt#L561-L590

**Comment by Sameeranjoshi** [comment]
> Perhaps missing `add_subdirectory(unittests)` in the top CMake script for Flang?

It seems like there are some unittests written without using gtest and they tend to use `ctest` 
Adding `add_subdirectory(unittests)` to top level CMakelists.txt fails the other tests present in directory.

```
CMake Error at llvm-proj/flang/unittests/Decimal/CMakeLists.txt:11 (add_flang_test):
  Unknown CMake command "add_flang_test".
```
Can we add only a single directory from unittests/ folder?
example, add_subdirectory(unittests/Optimizer)(This doesn't work anyways) or something similar? 

> Btw, the target that you've defined here is `FlangUnitTests` rather than `check-flang-optimizer` or `check-flang-unit` (i.e. try building `FlangUnitTests` instead).

I grepped for similar targets in llvm(`check-llvm-unit`) and mlir (`check-mlir-unit`) I couldn't find them.
So I chose the similar approach these projects tend to follow.
btw, how do we build `FlangUnitTests` target ?

**Comment by Sameeranjoshi** [comment]
> The flang/CMakeLists.txt file probably needs some more work. For example, clang has the following to set up its testing.
> 
> https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/clang/CMakeLists.txt#L561-L590

Similar approach lldb and lld, follow also we have `FLANG_INCLUDE_TESTS`  already in use in top level CMakelists.txt.

```
if(FLANG_INCLUDE_TESTS)
  add_subdirectory(unittests)
endif()

```
I might be wrong here but how does mlir work by just adding the directory without checks?
https://github.com/flang-compiler/f18-llvm-project/blob/72b6b1d3138646ba38b60fac9039e8daf90514be/mlir/CMakeLists.txt#L47

I think clang is mixing regression tests and unittests, where as we have a LIT based regression tests merged in.

I think the issue might be raise from the older gtest setup already in place and there is a ticket for porting them to gtest
https://github.com/flang-compiler/f18/issues/995

**Comment by kiranchandramohan** [comment]
Can this be added to llvm-project/flang?

**Comment by Sameeranjoshi** [comment]
> Can this be added to llvm-project/flang?

@kiranchandramohan Thanks.
I was unknown of any test to write and test the gtest infra using fortran language constructs, whereas I had read the `InternalNames.h` and I wanted to have some tests for them as a part of working for `fir-dev` branch, hence I thought of having a PR in `fir-dev`.

I will push the part except the fir test into `llvm-project/flang` once I have the setup working.
Does that sound reasonable?

**Comment by banach-space** [comment]
@Sameeranjoshi 
> we have FLANG_INCLUDE_TESTS already in use in top level CMakelists.txt.

I didn't notice that, my bad! So yes, you need `-DFLANG_INCLUDE_TESTS=On`.

Otherwise everything should be in place. Include paths for GTest are set in [add_unittests](https://github.com/llvm/llvm-project/blob/b2a485e37edf6415701c472d93afa7fa26dbcccb/llvm/cmake/modules/AddLLVM.cmake#L1382) (which you call [here](https://github.com/flang-compiler/f18-llvm-project/blob/c8417d83d7ed296a9ad2f0674463e3fca1a9bebb/flang/unittests/CMakeLists.txt#L5)). 

> I think the issue might be raise from the older gtest setup already in place

IIUC, there are currently only CTest tests in Flang (enabled [here](https://github.com/llvm/llvm-project/blob/b2a485e37edf6415701c472d93afa7fa26dbcccb/flang/CMakeLists.txt#L334)). I'm not aware of anything that would prevent CTest and GTest tests to co-exists.

> btw, how do we build FlangUnitTests target ?

`make FlangUnitTests` (or `ninja FlangUnitTests`) - that's after running `CMake` with `-DFLANG_INCLUDE_TESTS=On`. I hope this helps.

**Comment by kiranchandramohan** [comment]
@Sameeranjoshi That sounds OK to me. But consider the following if it is not too much work.

I was thinking that with unit tests, functions can be individually tested. If so it might be possible to test the name-mangling functions with what is already there in llvm-project/flang + Mangler.cpp, Mangler.h. And this does not require fir.

**Comment by schweitzpgi** [comment]
Merged after rebase.

**Pull request closed without merging**
