### PR TITLE
Add cast to avoid type mismatch errors on multiply op.

### PR DESCRIPTION
**Pull request by schweitzpgi**

### CODE REVIEW

**Review by mleair — APPROVED** [review]
LGTM

**Comment by sscalpone** [comment]
Don't we expect casts to be added in the front end (evaluate)?

**Comment by klausler** [comment]
> Don't we expect casts to be added in the front end (evaluate)?

Yes; the Expr<> structure isn't even capable of representing a multiplication of distinct types.

**Comment by jeanPerier** [comment]
@sscalpone and @klausler , when the multiply is a multiply from the Fortran code, lowering does rely on `Expr<>` to insert these converts as you mention. Here however, this is a multiply inserted low in the chain to implement stride/offset computations when making descriptors, so it is purely compiler generated code and I do not really see how the convert could be added by the front-end here.

**Pull request merged**
