### PR TITLE
[flang][fir] Add diagnostic tests for FIR ops verifier

### PR DESCRIPTION
**Pull request by clementval**
There are still a couple of diagnostics that are not reachable directly with `fir-opt` I think. Those are related to `fir.iterate_while` and `fir.do_loop`.

### CODE REVIEW

**Review by jeanPerier — APPROVED** [review]
Looks good to me, thanks !

**Review by schweitzpgi — APPROVED** [review]
Very nice. Would you also upstream this? Thank you.

**Comment by clementval** [comment]
> Very nice. Would you also upstream this? Thank you.

Yes this is the plan.

**Comment by clementval** [comment]
https://reviews.llvm.org/D97996

**Pull request merged**
