### PR TITLE
[flang] Adopt NoRegionArguments (WhereOp) and ParentOneOf (ResultOp) traits

### PR DESCRIPTION
**Pull request by jurahul**
Differential Revision: https://reviews.llvm.org/D83522

### CODE REVIEW

**Comment by schweitzpgi** [comment]
I tried building this patch against fir-dev and get a number of compilation failures.

```
[ 90%] Building CXX object tools/flang/lib/Optimizer/CMakeFiles/obj.FIROptimizer.dir/Dialect/FIROps.cpp.o
/work/flang/lib/Optimizer/Dialect/FIROps.cpp: In function ?mlir::LogicalResult verify(fir::ResultOp)?:
/work/flang/lib/Optimizer/Dialect/FIROps.cpp:1033:57: error: a function-definition is not allowed here before ?{? token
 static constexpr llvm::StringRef getCompareOffsetAttr() {
                                                         ^
/work/flang/lib/Optimizer/Dialect/FIROps.cpp:1037:56: error: a function-definition is not allowed here before ?{? token
 static constexpr llvm::StringRef getTargetOffsetAttr() {
                                                        ^
/work/flang/lib/Optimizer/Dialect/FIROps.cpp:1041:1: error: a template declaration cannot appear at block scope
 template <typename A, typename... AdditionalArgs>
 ^~~~~~~~
/work/flang/lib/Optimizer/Dialect/FIROps.cpp:1063:68: error: a function-definition is not allowed here before ?{? token
 static unsigned denseElementsSize(mlir::DenseIntElementsAttr attr) {
                                                                    ^
...
```

**Comment by jurahul** [comment]
Thanks. I have fixed it both here and on the LLVM Phabricator. But that means that the LLVM Phab review did not really build that change, which seems concerning. I have not verified by building locally.

**Comment by jurahul** [comment]
I have filed: https://bugs.llvm.org/show_bug.cgi?id=46751 (to investigate the why LLVM Phabricator did not flag this build failure).

**Comment by schweitzpgi** [comment]
Quick work. Thank you. I'll try the new changes.

Also thanks for filing the bug.

**Pull request merged**
