### PR TITLE
Add another folding regression test. This one for LEN.

### PR DESCRIPTION
**Pull request by schweitzpgi**

### CODE REVIEW

**Comment by schweitzpgi** [comment]
Test for #1432

**Review by klausler — CHANGES_REQUESTED** [review]
I think that concatenation is missing; e.g., LEN(c//d) is 20.

**Review by klausler — COMMENTED** [review]
Also, the modified file is not part of lowering, so it should be patched in llvm-project.

**Review by jeanPerier — APPROVED** [review]

**Review by vdonaldson — APPROVED** [review]

**Review by clementval — APPROVED** [review]
LGTM

**Comment by schweitzpgi** [comment]
Ping.

**Review by klausler — APPROVED** [review]
One more case: LEN(charScalar(-1:-999)) is 0.

**Comment by klausler** [comment]
Out-of-range substring bounds are valid when lower > upper, and produce a zero-length result.

**Pull request merged**
