### PR TITLE
[flang][openacc] Lower wait directive

### PR DESCRIPTION
**Pull request by clementval**

### CODE REVIEW

**Review by schweitzpgi — APPROVED** [review]
LGTM. What say the reviewers working on OpenMP?

**Comment by clementval** [comment]
@schweitzpgi Conflicts have been resolved. Might have new conflicts after merge of #526 #528 and #529

**Comment by clementval** [comment]
Looks like there is conflict. Can be merged when you want @schweitzpgi

**Comment by clementval** [comment]
> LGTM. What say the reviewers working on OpenMP?

Would be good to have their opinion. Lowering follows the same structure for all OpenACC ops. I'll do some refactoring work do reduce the code size a bit en reuse some code where clauses are shared.

**Comment by schweitzpgi** [comment]
I'm going to error on the side of getting your code in. If anyone has concerns or comments, we can always update the code.

**Comment by clementval** [comment]
Thanks for all the quick merge!

**Pull request merged**
