### PR TITLE
Cherry picks from llvm-project/main for #1008

### PR DESCRIPTION
**Pull request by banach-space**
12 patches cherry picked from the `main` branch of llvm-project that are required for https://github.com/flang-compiler/f18-llvm-project/pull/1008. I'm separating this from #1008 to make that PR self-contained and easier to review.

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
LGTM. All cherry-picks from upstream llvm-project/main.

**Review by kiranchandramohan — APPROVED** [review]

**Comment by jeanPerier** [comment]
I am seeing a lit test failure with my build config:
```
Failed Tests (2):
  Flang :: Driver/dump-all.f90
  Flang :: Driver/output-paths.f90
```

The more detailed message is below.

Here is my build config:
```
cmake ../llvm \
    -DFLANG_BUILD_NEW_DRIVER=Off \
    -DCMAKE_CXX_STANDARD=17 \
    -DLLVM_BUILD_TOOLS=On \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DLLVM_INSTALL_UTILS=On \
    -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=On \
    -DLLVM_ENABLE_PROJECTS="mlir;flang"
```

The errror seems related to ` -DFLANG_BUILD_NEW_DRIVER=Off `. Does this mean we will need to build the driver and clang after this cherry-picking ?

```
FAIL: Flang :: Driver/dump-all.f90 (27 of 1115)
******************** TEST 'Flang :: Driver/dump-all.f90' FAILED ********************
Script:
--
: 'RUN: at line 4';   build/bin/f18 -fdebug-dump-all f18-llvm-project/flang/test/Driver/dump-all.f90 2>&1 | build/bin/FileCheck f18-llvm-project/flang/test/Driver/dump-all.f90
--
Exit Code: 1

Command Output (stderr):
--
f18-llvm-project/flang/test/Driver/dump-all.f90:9:10: error: CHECK: expected string not found in input
! CHECK: Flang: parse tree dump
         ^
<stdin>:1:1: note: scanning from here
gfortran: error: unrecognized command line option '-fdebug-dump-all'; did you mean '-fdebug-cpp'?
^
<stdin>:1:5: note: possible intended match here
gfortran: error: unrecognized command line option '-fdebug-dump-all'; did you mean '-fdebug-cpp'?
    ^

Input file: <stdin>
Check file: f18-llvm-project/flang/test/Driver/dump-all.f90

-dump-input=help explains the following input dump.

Input was:
<<<<<<
           1: gfortran: error: unrecognized command line option '-fdebug-dump-all'; did you mean '-fdebug-cpp'? 
check:9'0     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
check:9'1         ?                                                                                              possible intended match
           2: execvp(gfortran) failed:  
check:9'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~
>>>>>>

--

********************
Testing:  0
FAIL: Flang :: Driver/output-paths.f90 (40 of 1115)
******************** TEST 'Flang :: Driver/output-paths.f90' FAILED ********************
Script:
--
: 'RUN: at line 6';   not build/bin/f18 -E -o build/tools/flang/test/Driver/Output/output-paths.f90.tmp.doesnotexist/somename f18-llvm-project/flang/test/Driver/output-paths.f90 2> build/tools/flang/test/Driver/Output/output-paths.f90.tmp
: 'RUN: at line 7';   build/bin/FileCheck -check-prefix=OUTPUTFAIL -DMSG='No such file or directory' -input-file=build/tools/flang/test/Driver/Output/output-paths.f90.tmp f18-llvm-project/flang/test/Driver/output-paths.f90
--
Exit Code: 1
```

**Review by schweitzpgi — COMMENTED** [review]
Works for me in my "eat your own dogfood" setup.

Adding some others though to see if they have build issues.

**Comment by clementval** [comment]
Works also on my side.

**Review by clementval — APPROVED** [review]

**Comment by banach-space** [comment]
Thank you all for reviewing and testing!

@jeanPerier , thanks for the summary! The two tests that are failing for you:
* `Driver/dump-all.f90`, and 
* `Driver/output-paths.f90` 

require the new driver (i.e. `-DFLANG_BUILD_NEW_DRIVER=On`). This issue does not exist on `main` as the new driver is always built, i.e. `-DFLANG_BUILD_NEW_DRIVER=Off` would be ignored. Note that for this PR I've only cherry-picked the patches that I need for #1008.

We can address the test failures in 2 ways:
1. Cherry-pick all driver related changes from `main`. This way everything should "just work", but this PR will get much bigger and you will have to build `clang` and the new driver (i.e. `-DFLANG_BUILD_NEW_DRIVER=Off` won't be an option).
2. Add a patch to this PR that disables the affected tests when `FLANG_BUILD_NEW_DRIVER` is `Off` (I'd have to add `! REQUIRES: flang-new-driver`). This would be a `fir-dev` specific workaround.

What is your preference? Perhaps there's some other way?

**Review by schweitzpgi — APPROVED** [review]

**Comment by jeanPerier** [comment]
> What is your preference? Perhaps there's some other way?

Thanks for confirming. Given our goal is to upstream, it's probably best to minimize fir-dev specific changes. I am fine removing my `-DFLANG_BUILD_NEW_DRIVER=Off`. After all, I am already doing this for builds from llvm branch.

**Review by jeanPerier — APPROVED** [review]

**Pull request merged**
