### PR TITLE
[sync] Sync worksharing-loop related patches in MLIR/OMPIRBuilder

### PR DESCRIPTION
**Pull request by PeixinQiao**
Sync worksharing-loop related patches in MLIR/OMPIRBuilder.

### CODE REVIEW

**Review by jeanPerier — COMMENTED** [review]
Thanks for syncing this. I can't assess if the `__kmpc_dispatch_init_4u` argument change in omp-wsloop-dynamic.f90 makes sense (1073741859 looks a weird number at first glance :) ). Please get approval from @kiranchandramohan or someone knowledgeable with kmpc here.

**Comment by kiranchandramohan** [comment]
@jeanPerier as @PeixinQiao points out it is the nonomonotonic modifier bitwise ORed with the dynamic schedule.
https://github.com/llvm/llvm-project/blob/main/openmp/runtime/src/kmp.h#L448
https://github.com/llvm/llvm-project/blob/aebe5fc6e7d8ab99f3796067d430752552932d28/openmp/runtime/src/kmp.h#L361

Yes, it is a really strange number.

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

**Review by jeanPerier — APPROVED** [review]
Thanks for explaining @PeixinQiao and @kiranchandramohan.

**Comment by kiranchandramohan** [comment]
All changes in this set of cherry-picks are in OpenMP related code and look OK to me. Merging.

**Pull request merged**
