### PR TITLE
Added missing function for bitwise intrinsics

### PR DESCRIPTION
**Pull request by zacharyselk**

### CODE REVIEW

**Comment by zacharyselk** [comment]
I am not 100% sure what I did but I think I reverted the commit.

**Comment by jeanPerier** [comment]
OK, the code looks good to me now ! Can I ask you to squash your commits into a single one (@schweitzpgi rebases this fork on a regular bases and that may help to not have merge commits from one branch to another in the history)

**Comment by zacharyselk** [comment]
Cool, I did not realize that you could do that. Alright it seems to be all squashed.

**Comment by jeanPerier** [comment]
> Do we need tests for other sizes of integers?

The other lit tests for intrinsics are not, I would favor having some kind of automated tests like the one for intrinsic operations to hammer all possible types rather than manually writing and maintaining tests for all type kind variants of the intrinsic calls. If it turns out too cumbersome to go for the generated tests, then yes, it would be good to add more (if not all) type variants here.

**Pull request merged**
